# Generated by Django 4.2.7 on 2023-11-10 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0004_alter_digitalcontent_platform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digitalcontent',
            name='platform',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='digital_content', to='watchlist_app.streamingplatform'),
        ),
    ]
