# Generated by Django 4.2.7 on 2023-12-06 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0005_alter_digitalcontent_platform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digitalcontent',
            name='platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='digital_content', to='watchlist_app.streamingplatform'),
        ),
    ]
